name: 2023_mdibl_fair
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - wget
  - fastp=0.23.2
  - fastqc=0.11.8
  - multiqc=1.14
  - salmon=1.9.0
  - snakemake=7.30.1
  - r-base=4.1.3
  - bioconductor-biocparallel
  - bioconductor-tximport
  - bioconductor-annotationhub
  - r-optparse
  - r-rprojroot
  - r-tidyverse
variables:
  CONDA_SUBDIR: osx-64
